import { useCallback, useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
const URL=import.meta.env.VITE_SERVER_URL||'http://localhost:3001'; const KEY='shadow_detective_session';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}; const save=v=>localStorage.setItem(KEY,JSON.stringify(v)); const clear=()=>localStorage.removeItem(KEY);
export function useShadowGame(){
 const socket=useRef(); const infoRef=useRef(); const [connection,setConnection]=useState('CONNECTING'); const [roomInfo,setRoomInfo]=useState(null); const [state,setState]=useState(null); const [privateState,setPrivateState]=useState(null); const [privateResult,setPrivateResult]=useState(null); const [timer,setTimer]=useState(0); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{infoRef.current=roomInfo},[roomInfo]); const fail=useCallback(e=>{setError(e||'เกิดข้อผิดพลาด');setTimeout(()=>setError(''),4500)},[]);
 useEffect(()=>{const s=io(URL,{transports:['websocket','polling'],reconnectionAttempts:10});socket.current=s;s.on('connect',()=>{setConnection('CONNECTED');const old=load();if(old&&!infoRef.current)s.emit('shadow:roomReconnect',old,r=>{if(r?.success){setRoomInfo({...r.room,playerId:r.playerId,reconnectToken:old.reconnectToken});setState(r.state);setPrivateState(r.privateState)}else clear()})});s.on('disconnect',()=>setConnection('DISCONNECTED'));s.on('shadow:roomUpdated',r=>setRoomInfo(p=>p?{...p,...r}:p));s.on('shadow:publicState',setState);s.on('shadow:privateState',setPrivateState);s.on('shadow:privateResult',setPrivateResult);s.on('shadow:timerTick',x=>setTimer(x.secondsRemaining));s.on('shadow:terminated',()=>{setState(null);setPrivateState(null)});s.on('shadow:roomClosed',()=>{clear();setRoomInfo(null);setState(null)});return()=>s.disconnect()},[]);
 const emit=useCallback((event,payload)=>new Promise((resolve,reject)=>{socket.current?.emit(event,payload,r=>{if(r?.success)resolve(r);else{fail(r?.error);reject(new Error(r?.error))}})}),[fail]);
 const create=async playerName=>{setLoading(true);try{const r=await emit('shadow:roomCreate',{playerName});const v={roomId:r.roomId,playerId:r.playerId,reconnectToken:r.reconnectToken};save(v);setRoomInfo({...r.room,...v})}finally{setLoading(false)}};
 const join=async(roomId,playerName)=>{setLoading(true);try{const r=await emit('shadow:roomJoin',{roomId,playerName});const v={roomId:r.roomId,playerId:r.playerId,reconnectToken:r.reconnectToken};save(v);setRoomInfo({...r.room,...v})}finally{setLoading(false)}};
 const withRoom=(event,data={})=>emit(event,{roomId:infoRef.current?.roomId,...data});
 const leave=()=>{if(infoRef.current)socket.current?.emit('shadow:leave',{roomId:infoRef.current.roomId});clear();setRoomInfo(null);setState(null);setPrivateState(null)};
 return {connection,roomInfo,state,privateState,privateResult,setPrivateResult,timer,error,loading,create,join,leave,start:()=>withRoom('shadow:roomStart'),action:(action,targetPlayerId,evidenceId)=>withRoom('shadow:action',{action,targetPlayerId,evidenceId}),beginVote:()=>withRoom('shadow:beginVote'),vote:targetPlayerId=>withRoom('shadow:vote',{targetPlayerId}),terminate:()=>withRoom('shadow:terminate'),close:()=>withRoom('shadow:roomClose')};
}
